docker/libcontainer

cgroups/fs/stats_util_test.go
integration/template_test.go

I calmed `vet` about `libcontainer.Namespace` because it is very suspicious about types from other packages.

Fix vet errors

---

Dockerfile

Ran the tests locally using the image based off golang:1.4 and they succeeded.
Signed-off-by: Mrunal Patel <mrunalp@gmail.com> (github: mrunalp)

Changes Dockerfile to use go 1.4

---

integration/exec_test.go
namespaces/exec.go

If we stop using the PID namespace, and more then one process is running
when the pid 1 exits, docker will hang since the cgroups do not disappear.
This code will kill all remaining processes
Add Tests for handing of Pid Namespaces

killall processes in a cgroup if you are not using the pid namespace

---

namespaces/exec.go
sample_configs/host-pid.json

This adds a sample config for running a process in the hosts PID namespaces and refactors the `killAllPids` function to avoid two calls to FindProcess

Refactor kill all pids

---

ROADMAP.md

Adds POWER (ppc64 and ppc64le), System z (s390x), and ARM to list of
architectures currently supported by libcontainer
Docker-DCO-1.1-Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com> (github: estesp)

Update ROADMAP.md to correctly reflect current arch status

---

nsinit/main.go
nsinit/oom.go

This adds the ability to receive OOM notifications for a container via
the `nsinit oom` command.

Add nsinit command to display oom notifications

---

cgroups/fs/apply_raw.go

cgroups: don't change a freezer state if an operation failed

---

namespaces/execin.go
namespaces/nsenter/nsenter.c
namespaces/nsenter/nsenter_test.go

This allows the parent to place the process into cgroup first before spawning the user process.

nsenter waits for parent signal before forking

---

cgroups/fs/apply_raw.go

My previous patch moved the setting of the freezer state after the Set()
command. It's wrong, because this command uses it, so we need to set the
freezer state before the command and rollback it in an error case.
Fixes: 13a5703d853f ("cgroups: don't change a freezer state if an operation failed")

cgroups: set a freezer state before calling FreezerGroup.Set()

---

namespaces/init.go
namespaces/utils.go

In a config file we specify which namespaces have to be created and which configuration have to be applied for them. Currently if a configuration is specified without a proper namespace, it is applied to the host namespace. It's unexpected behavior, isn't it?
With these patches we will get an error if a config file contains configuration without a proper namespace.

namespace: don't change namespaces which are not belonged to the CT 

---

mount/init.go
mount/mount_config.go
mount/pivotroot.go

This allows users to prepare a read only filesystem with only a few writable subpaths inside it, to be used as the root filesystem by containers.
In particular, read only loopback images can now be used as the root filesystem, allowing multiple containers to share the same base (root) image and share pages without necessarily doing CoW layers.
All changes are backwards compatible, AFAICT. More details in commit messages.
Signed-off-by: Fabio Kung <fabio@heroku.com> (github: fabiokung)

Support read-only root filesystems

---

namespaces/exec.go

Issue with cmd.Wait is that it is waiting for closing pipes and if we
have forked processes which inherited pipes from parent, then we need to
kill them to unblock cmd.Wait.
Should fix docker/docker#10303
Now idea is next:
- Wait4 for init process dead
- Kill remaining processes in cgroup (pipes closed as side effect)
- use cmd.Wait for waiting pipes flushed to client
Signed-off-by: Alexander Morozov <lk4d4@docker.com>

Use Wait4 instead of cmd.Wait

---

namespaces/execin.go
namespaces/nsenter/nsenter.go
namespaces/nsenter/nsenter_test.go
namespaces/nsenter/nsexec.c

Currently nsexec() creates a proxy process to enter into a pid namespace.
It isn't good, because we need to proxy an exit code and signals.
We can use CLONE_PARENT to fork a process with the right parent.

nsenter: remove a proxy process

---

cgroups/systemd/apply_systemd.go

This is the same behavior as fs does.

cgroups: always create device cgroup on systemd

---

docs/man/nsinit.1.md

We ship `nsinit` along with `docker-io` package on our RHEL distributions. However there is no man page for it. It would be nice for our customers to do `man nsinit`.

Created man page for nsinit

---

security/capabilities/capabilities.go
update-vendor.sh
vendor/src/github.com/syndtr/gocapability/capability/capability.go
vendor/src/github.com/syndtr/gocapability/capability/capability_linux.go

The gocapability package uses /proc/PID/status to get a bounding set.
If a container uses pidns without mntns, it sees /proc from the host
namespace, but the process doesn't know its own pid in this namespace.
In this case it can use /proc/self/status, which is always the right one.
Signed-off-by: Andrew Vagin <avagin@openvz.org>

namespaces: allow to use pid namespace without mount namespace

---

namespaces/nsenter/nsenter.c

When running under child subreaper mode, it's useful for nsenter to be able to reap child processes. We have seen cases where spawned user processes were not reaped properly (https://github.com/creationix/nvm/issues/650)
I dont see how we can write a test case for this yet. Manual steps to reproduce this are:
```
> docker pull soareschen/ubuntu-zsh
> docker run -it --rm --name test-nvm soareschen/ubuntu-zsh zsh
> source ~/.nvm/nvm.sh
> ps auxf # no defunct processes
> docker exec -it test-nvm zsh
> source ~/.nvm/nvm.sh
> ps auxf # lots of defunct processes before this patch, and no defunct processes after
```
Thanks @soareschen for the test image

handle SIGCHLD when running as child subreaper

---

network/types.go
network/veth.go

We're throwing a new attempt at removing the userland proxy from Docker. The blocking issue we discovered last time was that hairpin NAT was not available on some systems (see docker/docker#9134).
This PR reintroduces @phemmer work from #62 and adds the ability to enable Hairpin NAT on a per-network basis using the `Network.HairpinNAT` flag (disabled by default).

Resurrect hairpin NAT

---

nsenter/nsenter.go

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65134
Workaround suggested by iant
Reported here https://github.com/docker/docker/issues/9207#issuecomment-75354189
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

nsenter: noop reference to C constructor

---

container.go
container_linux.go
error.go
integration/exec_test.go
integration/execin_test.go
integration/utils_test.go
nsinit/exec.go
process.go
process_linux.go

Currently we have a problem when buffers are used for std file
descriptors.  These buffers are filled from goroutines (Cmd.goroutine),
and we need to wait them to be sure that all data have been copied.
Signed-off-by: Andrew Vagin <avagin@openvz.org>

process: add Wait() and Pid() methods

---

container.go
container_linux.go
container_test_linux.go

I think this is more convenient because for working with namespaces we
using configs.NamespaceType.

Use configs.NamespaceType as key for State.NamespacePathes

---

configs/config.go

Because container.Config() returns values and you can't get pointer from
function call immediately. So it is impossible to call
container.Config().HostUID().

Make possible to call config methods on values

---

nsinit/exec.go
nsinit/utils.go

Adds missing exit to fatal function.
Extracts ProcessState when we get ExitError.

Exit related cleanup

---

rootfs_linux.go

In docker we evaluate all symlinks im path to check that they  not escaping
from rootfs and that gives us full path to mount.

Don't join rootfs if path already prefixed by it

---

network_linux.go
stats.go

In other case it is impossible to implement Stats() method from
interface outside libcontainer.

Make NetworkInterface public

---

container_linux.go
generic_error.go
process.go

`genericError` constructor should not panic when we pass in nil error, but we should not pass nil error actually. This fixes it.

Fix panic when genericError constructor gets nil error

---

notify_linux.go

In function notifyOnOOM,it do the open file operations but do not be close before return,so close file operations should be added to release resource.

Add the file close operation before function return to release resource

---

cgroups/fs/apply_raw.go
cgroups/fs/freezer.go

So Apply function of freezer can be as sample as other subsystems.

cgroups: use Set instead of Apply in Freeze

---

nsenter/nsenter_test.go

It lead to some race which hanged test.

Remove overcomplicated logic of SIGCHLD from TestNsenterDeadPid

---

cgroups/fs/memory.go
cgroups/fs/memory_test.go
configs/cgroup.go

Redo #412 
This patch add support for diable OOM Killer.
Signed-off-by: Hu Keping <hukeping@huawei.com>

cgroups: add support for oom control

---

cgroups/fs/apply_raw.go
cgroups/utils.go

Find cgroup mountpoint dir through a specific subsystem is not reliable,
we don't know which subsystem users will or will not mount, we can't
assume that, only we can assume is that users mount cgroup subsystems
on the same dir.

fix apply error when we not mount cpu subsystem

---

nsenter/nsenter.go
nsenter/nsenter_gccgo.go

The change 699429e60f23ab0fa3bdd97b6326316be08791ad that allows the
constructor attribute to not be optimized out on gccgo has resulted in a
warning when compiling on the golang compiler.
```
./nsenter.go: In function ‘_cgo_51505a0edd5d_Cfunc_init’:
./nsenter.go:40:49: warning: unused variable ‘a’ [-Wunused-variable]
```
the generated code produced an unused struct like:
```
void
_cgo_d6cfae95ae01_Cfunc_init (void *v)
{
struct
{
char unused;
} __attribute__ ((__packed__, __gcc_struct__)) * a = v;
init ();
}
```
Truly the "fix" would be upstream in cgo. If it knows it is producing an
unused struct, then it should also include __attribute__ ((unused))
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

nsenter: fix the -Wunused-variable warning

---

cgroups/fs/apply_raw.go
cgroups/fs/blkio.go
cgroups/fs/cpu.go
cgroups/fs/cpuset.go
cgroups/fs/devices.go
cgroups/fs/devices_test.go
cgroups/fs/freezer.go
cgroups/fs/memory.go
cgroups/fs/util_test.go

1. add subsystem mounted check in `d.path()`, so we can really get `IsNotFound` error and skip `Set`.
2. cgroup unit test use temp path, not real cgroup path, so we should create the path by `filepath.Join()` instead of `d.path()`.

fix some cgroups issues

---

rootfs_linux.go

mqueue shouldn't be labeled when mounting; otherwise, the mount will
fail.
Signed-off-by: Andy Goldstein <agoldste@redhat.com>

Don't label mqueue when mounting

---

factory.go
factory_linux.go
factory_linux_test.go

I need this for `docker info` don't want to use type assertions because actually `LinuxFactory` should be private.

Add information Type method for Factory

---

configs/network.go
network_linux.go

Resurrect #366 which was apparently lost in the API rework.

Hairpin NAT network configuration

---

Dockerfile

Move up to the latest busybox tarball that has the fix for `ip` command
segfault.
Docker-DCO-1.1-Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com> (github: estesp)

Update to recent busybox 2014.11 tar

---

selinux/selinux.go

selinux: Adds a check for a NUL byte at the end of the string and removes it

---

Dockerfile

That script was moved a few days ago
https://github.com/docker/docker/pull/11373
Signed-off-by: Andrew Vagin <avagin@openvz.org>

Fix path to /dind

---

rootfs_linux.go

mount: sysfs also doesn't need to be labelled like mqueue.

---

cgroups/fs/apply_raw.go
cgroups/fs/cpuset.go

As of now if the parent cgroup path is absolute, we expect the cgroups to exist. If it is not absolute, everything works as expected.

Do not fail cgroups setup if parent cgroup does not exist.

---

container.go
container_linux.go

We only have libcontainer.Container on Docker side, can't change `config`
in linuxContainer, pass config to libcontainer so we can change config of
container.

add parameter to Set api

---

cgroups/systemd/apply_systemd.go

on systemd v208 in Centos7 and Fedora20 error is not:
"org.freedesktop.DBus.Error.PropertyReadOnly"
but:
"property.org.freedesktop.DBus.Error.PropertyReadOnly"
so check failes and in Docker we get:
Docker daemon: System error: Cannot set property DefaultDependencies, or
unknown property
Fix for commit:
https://github.com/docker/libcontainer/commit/99233fde8c4f58853a474a5831ef0bcf6bf866c5
Signed-off-by: Pavel Tikhomirov <ptikhomirov@parallels.com>

systemd: properly check DefaultDependencies is read only

---

cgroups/fs/apply_raw.go

This error is not propogated up to the caller and needs to be handled at
the site where d.path() is called.

path now returns the IsNotFound error

---

cgroups/fs/apply_raw.go
cgroups/fs/blkio.go
cgroups/fs/cpu.go
cgroups/fs/devices.go
cgroups/fs/freezer.go
cgroups/fs/memory.go

We need to do this so that when a user specifies an option and we are unable to fulfill the request we should fail hard instead of ignoring the error and keep going.  We also need to fail hard for cgroups like `devices` because of security reasons.

Revert "cgroups: only return path when subsystem really mounted

---

update-vendor.sh
vendor/src/github.com/syndtr/gocapability/capability/capability_linux.go

It includes fix for RHEL6 which has no cap_last.

Update syndtr/gocapability to 8e4cdcb3c22b40d5e330ade0b68cb2e2a3cf6f98

---

cgroups/fs/apply_raw.go

Now we return not found err in path(), so no need to check again.

remove redundant code

---

container_linux.go
init_linux.go
integration/exec_test.go
process.go

This allows a process to override the capabilities specified in the container config. This could allow one to run more/less privileged processes in a container. For e.g. to examine logs or modify iptables.

Process capabilities

---

process_linux.go

We need this to unmask syscall.ESRCH error, which handled in docker and
can be handled by other clients.
Closes #457

Use syscall.Kill instead of p.cmd.Process.Kill

---

nsinit/README.md

Cut the long lines and add `--config` to the `nsinit exec` command.

fix README.md for nsinit

---

container_linux.go
init_linux.go
standard_init_linux.go

For some reason when the supervisor of a container is PID1 the parent
death signal was being delivered to the container's init process even if
it did not die.  Also the ppid() will return 1 for a container running
in the pid namespace of it's parent and the parent is pid1.
Fixes: https://github.com/docker/docker/issues/12015

Fix pdeathsig and ppid for supervisor running as pid1

---

.gitignore
Makefile
README.md

This adds `make binary` to perform direct install libcontainer binaries inside `dockercore/libcontainer` container instead of having to install dependencies and run `make direct-install` on the host.
The `nsinit` binary will be placed into `bundles/nsinit`, and we ignore the bundles directory from git.

add binary target to direct install in a container

---

cgroups/systemd/apply_systemd.go

1. freezer status should not change if freeze failed.
2. reduce redundant code.

bugfix and cleanup for systemd cgroup

---

container_linux.go
factory.go
factory_linux.go
init_linux.go
integration/exec_test.go
integration/init_test.go
nsinit/init.go
process.go

This takes the work done in #496 and changes this so that we append the childPipe to the end of the processes FD set.  We provide an internal env var for identifying the childPipe's fd to the init process and any of the user defined extra files will be exactly how they specify them.  
Closes #496

Append childpipe for adding addtional Fds to container

---

label/label_selinux.go
label/label_selinux_test.go

Currently relabel requires an exact match on passed in relabel string.  This patch will allow the passing of multiple params in the string, and just look for Z or z

Add value checking on relabel command for selinux

---

cgroups/fs/memory.go
cgroups/fs/memory_test.go
cgroups/stats.go

This replaces #506
I don't think we want to subtract the cache from the usages as that is the real usage.  The clients can use this information how they please and subtract the cache if desired. 
Closes #506

Add cache to MemoryStats

---

system/setns_linux.go
system/syscall_linux_64.go

The ARMv8 commit should be self-explanatory.
The ARMv7 commit is fixing something that's been wrong since day 1, though the lack of complaints due to it probably shows how often this code-path isn't followed on ARM.  Still, I saw it in passing and fixed it anyway.
The PowerPC commit is similarly self-explanatory to the ARMv8 one, though also shows that syscall_linux_64.go is fairly poorly named.  Really, syscall_linux* should probably go away and be replaced by an import C that calls the glibc setuid() and setgid() wrappers, since they magically always hit the right syscall, and we don't have to have knowledge of what arch supports what, but I went for the most minimally invasive fix here just to make it build happily.
Tested as backports to docker 1.5.0 on amd64, i386, armhf, arm64, …

Add arch support for ARMv8 and PowerPC, and fix ARMv7

---

configs/config.go
rootfs_linux.go

As an admin I would expect that if I volume mount a partition into a container, and then later add a mount point to the volume, it will show up in the container.

Change mount point propogation to default to slave

---

cgroups/fs/apply_raw.go
cgroups/systemd/apply_systemd.go

If I pass a value for `cpu-shares` larger than the maximum allowed value, the kernel just changes it to the maximum allowed value. This is confusing for the user as what he requested and what is set is different.
e.g. if the max possible value is 262144 and I tried to set cpu-shares as 280000, 
This code will throw an application error saying "The maximum allowed cpu-shares is 262144".

Throw an error if cgroup tries to set cpu-shares more/less than the maximum/minimum permissible value.

---

integration/execin_test.go

Otherwise a container cannot be destroyed and we will get an error
in the next case:
go test -v .
=== RUN TestExecPS
--- FAIL: TestExecPS (0.02s)
exec_test.go:43: <nil>: [0] Id already in use: Container with id exists: testCT
Cc: @LK4D4 

integration: wait all test processes

---

apparmor/apparmor.go

In ubuntu 14.04, Apparmor is installed by default. When uninstalling apparmor with `apt-get purge apparmor`, `/sbin/apparmor_parser` will be delete. However, `/sys/kernel/security/apparmor` and `/sys/module/apparmor/parameters/enabled` remains on the host, resulting in the following error
```
FATA[0000] Error loading docker apparmor profile: fork/exec /sbin/apparmor_parser: no such file or directory () 
```

check "/sbin/apparmor_parser" in apparmor.IsEnabled()

---

label/label_selinux.go
label/label_selinux_test.go

While we know this is by no means complete it at least stops users from
doing a common ignorant action. rm -rf /  has a similar protection.

We want to prevent users from accidently attempting to relabel /, /etc and /usr

---

container_linux.go

CRIU has following requirements for a container root:
* it is a mount point
* a parent mount point isn't over-mounted

cr: prepare a container root

---

container_linux.go

This code was added when images were saved in a factory root directory and in
addition this directory was used as a flag.
Now an user can decide when images can be removed.
Cc: @boucher

cr: don't remove images after restore

---

integration/exec_test.go

Made a mistake before, freeze test doesn't use newContainer,
systemd test doesn't actually work.

fix freeze systemd test

---

configs/mount.go
integration/exec_test.go
rootfs_linux.go

We want to allow docker to mount tmpfs directories over existing directories
in the image.  We will use this patch to pass commands from docker to
libcontainer.  The first command we will use is the tar command to gather
all of the contents of the destination directory before mounting, then after
we mount the post mount command will untar the content.

Add support for Premount and Postmount commands.

---

container_linux.go

This change was necessary for me to get criu/libcontainer running inside of Docker.

Exclude the root path from mount point paths.

---

process_linux.go

We already doing this in initProcess
This will be fix for docker/docker#12627

Check for cmd.Process not-nilness in setnsProcess.terminate()

---

container_linux.go
netlink/netlink_linux.go
network_linux.go

We need to enumirate all veth devices on restore and handle
{un,}lock-network notifications.

cr: add network support

---

cgroups/fs/devices.go
cgroups/fs/devices_test.go
cgroups/systemd/apply_systemd.go
configs/cgroup.go

the original code usee cgroup devices, like:
group        whitelist entries                        denied devices
A                "c x:x rwm", "b x:* rwm"                 all the rest
I add another use method, you can pass parameters, like:
group        whitelist entries                        denied devices
A                all                                            "c x:x rwm", "b x:* rwm"

cgroups: add support of devices deny for another use of cgroup devices

---

container.go
container_linux.go
criu_opts.go
nsinit/checkpoint.go
nsinit/restore.go

In order to do more complex things with checkpointing and restoring of containers it's necessary to have control over where the image files are being saved and whether or not to kill the running process. It's possible more flags will be wanted in the future. Some things probably should always be auto-configured by libcontainer though.
I'd be glad to hear any suggestions for alternate solutions here. This is my first contribution.

Add support for providing options to CRIU.

---

cgroups/systemd/apply_systemd.go

I think the remove code and devices.Set do the same things.

cgroups/systemd: remove useless code

---

configs/namespaces.go
configs/namespaces_syscall.go
configs/namespaces_syscall_unsupported.go

libcontainer/configs is used by the docker user namespace proposed
patchset to use IDMap for uid/gid maps across the codebase.  Given the
client uses some of this code, it needs to build on non-Linux.  This
separates out the Linux-only syscalls using build tags.
Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com> (github: estesp)

Split namespace syscall content for building on non-Linux

---

configs/config.go
integration/exec_test.go
rootfs_linux.go
standard_init_linux.go

This allows one to do the equivalent of sysctl -w ip.ipv4.ip_forward 1 or any such property.
I will add tests and other bits if we are okay adding this.

Adds support for setting system properties.

---

.gitignore

It's auto generated by go install, we should ignore them.

add vendor/pkg to gitignore

---

rootfs_linux.go
rootfs_linux_test.go

Mounts in /sys like /sys/fs/cgroup are valid and should be allowed at
the libcontainer level.

Do not prevent mounts in /sys

---

cgroups/fs/apply_raw.go
cgroups/fs/cpu.go
cgroups/fs/cpuset.go
cgroups/fs/devices.go
cgroups/fs/memory.go
cgroups/systemd/apply_systemd.go

We do this aim two goals:
- don't fail when some subsystems are not mounted.
- fail hard instead of ignoring the error when a user specifies
an option and we are unable to fulfill the request.

don't fail when subsystem not mounted

---

container_linux.go

container.Checkpoint() doesn't clear c.initProcess and it's used on restore. A restored process is set from criuNotifications().
Cc: @boucher

container: don't use c.initProcess before it's set

---

stacktrace/frame.go

According to https://golang.org/src/runtime/symtab.go?s=3423:3455#L94
It is possibile that runtime.FuncForPC() returns nil, don't know how
but I do met this problem when some kernel config problems cause
`p.createNetworkInterfaces` return error.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0]
goroutine 74 [running]:
github_com_docker_libcontainer_stacktrace.NewFrame
/go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/stacktrace/frame.go:12
github_com_docker_libcontainer_stacktrace.Capture
/go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/stacktrace/capture.go:18
libcontainer.newSystemError
/go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/generic_error.go:48 …

Fix stacktrace panic

---

nsenter/nsenter_unsupported.go

Commit 4d1d6185abda6a5d43eac75f77242488b81f8937 added this nsenter_unsupported.go file in order for nsenter to be a valid (but empty, non-functional) Go package on unsupported platforms. However, on such platforms, Go still complains because there exists a .c file in this folder, but the package doesn't use cgo.
Fix that by importing "C" pseudo-package.
I don't see any other ways of fixing this, since you can't add build tags to the .c file. But if someone has any additional thoughts here, please comment.
To illustrate the issue, if you are on OS X, which is an unsupported platform, and you do this innocent Go command to update the libcontainer package source to latest version (without building):
```
$ go get -u -d github.com/docker/libcontainer/...
package github.com/docker/libcontainer …
```

Fix nsenter package on unsupported platforms.

---

netlink/netlink_linux.go

If the seed was not seted, all machines get the same MAC address.
Then technique like Open vSwitch won't work due to the same MAC address
of all machines.

Set the seed when randMacAddr

---

nsinit/config.go

```
[root@localhost busybox]# nsinit exec -t --sys-prop "kernel.shmmni=8000" sh
/ # 
/ # cat /proc/sys/kernel/shmmni 
8000
```

Add a flag for specifying system properties.

---

container_linux.go

The format of criu version is X.Y[.Z]. The current code can not parse X.Y,
because scanf returns the "input does not match format" error.

cr: fix parsing of criu version

---

console_freebsd.go

Whan trying to compile docker on FreeBSD, i'm recieving build error because console functions are implemented for linux only. Created a stub to silence this.

Process.go can compile on FreeBSD

---

utils/utils.go
utils/utils_test.go

If TestGenerateName() accept size parameter larger than 64, it will panic.
This patch fix this potential panic bug.
Signed-off-by: Zhang Wei <zhangwei555@huawei.com>

bug fix: slice bounds out of range

---

SPEC.md

I was following `SPEC.md` while setting up mount points for a container manually and noticed a couple of things that had to be changed in order for the `mount` calls to succeed.  "shm" is not a valid file system type, and there must be an "=" between "gid" and "5" in the devpts options.  I experienced these issues on Linux 4.0.4.

spec: Fix errors in file system mount points table.

---

README.md

The dockerproject.com domain is moving to dockerproject.org this changes the buildstatus link to point to the new domain.
For reference, see https://github.com/docker/docker/pull/13709

Update dockerproject.com links

---

configs/config_unix.go
configs/device_defaults.go
configs/namespaces_unix.go
devices/devices_unix.go
devices/number.go
stats_freebsd.go
system/sysconfig.go

Libcontainer codebase has changed, fixing broken FreeBSD build.

make libcontainer compile on freebsd (again)

---

cgroups/systemd/apply_systemd.go

It totally fixes leftover ".scope" fails. Of course it's just
workaround, real issue seems to be in go-systemd library or in systemd
itself.
I tried latest commit from `coreos/go-systemd` and it has same issue.
ping @philips looks okay for you as workaround?

Stop systemd unit on destroy

---

label/label_selinux.go

Current libcontainer in docker-1.7 will not allow you to volume mount /, /etc, and /usr into a container.  You even if you have not asked SElinux to relabel.  This patch will allow you to mount if you did not ask to relabel.
Needs to be cherrypicked into your docker-1.7 release.

Fix relabel to allow volume mounting of /

---

console_linux.go
nsenter/nsexec.c
rootfs_linux.go

Convert syscall.Dup2 calls to syscall.Dup3.  The dup2 syscall is depreciated
and is not available on some architectures.  Fixes build errors like these when
building for arm64:
console_linux.go: undefined: syscall.Dup2
Signed-off-by: Geoff Levand <geoff@infradead.org>

linux: Convert dup2 calls to dup3

---

configs/config.go
init_linux.go
integration/exec_test.go
nsinit/config.go
user/user.go
user/user_test.go

Original PR #559:
> This PR modifies AdditionalGroups to be a string array and the lookup to translate to group ids is performed in the container as discussed in docker/docker#10717
Signed-off-by: Mrunal Patel mrunalp@gmail.com
This carries #559, did a rebase and implement the group lookup by scanning through the group file only once.
@mrunalp Can you take a look if this looks good ? I cant open the PR back to the original because of the rebase.

Rebased: Additional groups lookup

---

cgroups/fs/memory.go
cgroups/fs/memory_test.go
cgroups/systemd/apply_systemd.go

As discussed in https://github.com/docker/libcontainer/issues/616,
remove this logic in libcontainer.

Don't change memswap value in libcontainer

---

netlink/netlink_linux_armppc64.go
netlink/netlink_linux_notarm.go

Proposed fix for https://github.com/docker/docker/issues/13856
ppc64 & ppc64le share the same return data type as the arm architecture for the ifrDataByte call.
This change adds build tags to implement that change. 
Signed-off-by: Michael Chase-Salerno <bratac@linux.vnet.ibm.com>

Additional ppc architectures follow the arm datatype

---

nsenter/nsexec.c

On some older Fedora distros `SYS_setns` was not defined, but `__NR_setns` is a usable replacement.
Signed-off-by: Benoit Sigoure <tsunanet@gmail.com>

Handle SYS_setns not existing but __NR_setns does.

---

hack/validate.sh
update-vendor.sh
vendor/src/github.com/golang/protobuf/proto/all_test.go

I changed hash for gocapability and re-run vendor script. Also I change vet validation to use docker version, which run vet only on changed files to skip `golang/protobuf` warning.
We discovered those issues in #633

Fix some suspicious things in vendor

---

cgroups/fs/memory.go
cgroups/systemd/apply_systemd.go
integration/exec_test.go

Currently we can't start container with kmem limit, because we
set kmem limit after processes joined to cgroup, we'll get device
busy error in this case.
Fix it by moving set before join.

Fix kmem limit set

---

cgroups/fs/apply_raw.go

Even if cpu cgroup controller is enabled it's still possible that
cpu.shares doesn't exist.
This is the case when the kernel config has CONFIG_CGROUP_SCHED
enabled but CONFIG_FAIR_GROUP_SCHED disabled. Then docker fails to
start containers even --cpu-shares isn't specified.
$ sudo docker run -i -t ubuntu:14.04
Error response from daemon: Cannot start container 5600ae87eb9d0eca49f6bcee012247d6b4beb49c426d6cf17e2456279f9311f6: [8] System error: open /sys/fs/cgroup/cpu/docker/5600ae87eb9d0eca49f6bcee012247d6b4beb49c426d6cf17e2456279f9311f6/cpu.shares: no such file or directory
Signed-off-by: Zefan Li <lizefan@huawei.com>

Avoid trying to access cpu.shares when it doesn't exist

---

nsinit/config.go

As it relates to issue #639, this at least adds the initialization of the default "MemorySwappiness" value to `-1` for the "nsinit" consumer/interface to libcontainer, and also adds the ability for the user to set the swappiness factor on the `nsinit` command line.
This is an analog to Docker PR docker/docker#14030.
Docker-DCO-1.1-Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com> (github: estesp)

Fix nsinit to configure default cgroup entry for MemorySwappiness

---

cgroups/fs/cpuset.go

Even if libcontainer does not create the directories for the cpuset
cgroup we should ensure that they are properly populated with the
parent's cpus and mems values.  Some systems create the directory
structures but do not correctly populate the values and causes our
implementation to fail.
The change in this code is that instead of stopping when we find the first parent directory in `cpuset`, we keep moving up the hierarchy until we hit the root of the `cpuset` cgroup to ensure that every parent is correctly created. 

Ensure all parent dirs are properly setup
