docker/libcontainer

- cgroups/fs/apply_raw.go
- cgroups/utils.go
Signed-off-by: Victor Marmol <vmarmol@google.com>
> Don't get stats for cgroups that don't exist.

- config.go
- namespaces/init.go
A stab at https://github.com/docker/docker/issues/9360
Signed-off-by: Mrunal Patel <mrunalp@gmail.com> (github: mrunalp)
> Adds functionality to specify additional groups to join.

- namespaces/exec.go
Test the process `WaitStatus` for a signal, and return an exit code of [128 + signal which killed the process](http://tldp.org/LDP/abs/html/exitcodes.html).
Fixes docker/docker#9979.
> Fix exit codes when dying on a signal

- update-vendor.sh
- vendor/src/github.com/golang/glog/LICENSE
- vendor/src/github.com/golang/glog/README
- vendor/src/github.com/golang/glog/glog.go
- vendor/src/github.com/golang/glog/glog_file.go
- vendor/src/github.com/golang/glog/glog_test.go
Signed-off-by: Mrunal Patel <mrunalp@gmail.com> (github: mrunalp)
> Vendors glog dependency for the api branch.

- integration/exec_test.go
- integration/init_test.go
> new-api: integration: check that a process can be executed in an existing CT

- namespaces/execin.go
- namespaces/init.go
Follow on to #324 
Signed-off-by: Mrunal Patel <mrunalp@gmail.com> (github: mrunalp)
> Checks namespace flags for user ns code path.

- cgroups/cgroups.go
- cgroups/fs/blkio.go
- cgroups/systemd/apply_systemd.go
> add support for blkio.weight

- namespaces/exec.go
Signed-off-by: Guo Xiuyan <guoxiuyan@huawei.com>
> Fix a minor typo

- update-vendor.sh
- vendor/src/github.com/godbus/dbus/CONTRIBUTING.md
- vendor/src/github.com/godbus/dbus/MAINTAINERS
- vendor/src/github.com/godbus/dbus/conn.go
- vendor/src/github.com/godbus/dbus/introspect/introspect.go
- vendor/src/github.com/godbus/dbus/introspect/introspectable.go
- vendor/src/github.com/godbus/dbus/prop/prop.go
- vendor/src/github.com/godbus/dbus/transport_unix.go
- vendor/src/github.com/godbus/dbus/transport_unixcred_dragonfly.go
- vendor/src/github.com/godbus/dbus/transport_unixcred_linux.go
- vendor/src/github.com/godbus/dbus/variant.go
Also, now we can set `go vet` in CI. I'll do this in separate PR.
> Update github.com/godbus/dbus to v2

- cgroups/systemd/apply_systemd.go
The root problem this fixes is the docker daemon uses DefaulDependencies
for all of its scopes which means that the containers get killed by
systemd before the docker daemon is notified to shutdown. This means
that a docker run in a service file won't get ordered properly on
shutdown! This has affected many CoreOS users and is documented in
systemd as so:
"Unless DefaultDependencies=false is used, scope units will implicitly
have dependencies of type Conflicts= and Before= on shutdown.target."
Unfortunately, systemd didn't allow setting DefaultDependencies=false on
transient units until today:
systemd-run --scope --property="DefaultDependencies=false" /usr/bin/sleep 50000
Unknown assignment DefaultDependencies=false.
Failed to create message: Invalid argument
Fixed here: …
> cgroups: systemd: set DefaultDependencies=false if possible

- cgroups/fs/apply_raw.go
This will allow late-binding of the cgroup hierarchy.
Signed-off-by: Victor Marmol <vmarmol@google.com>
> Retry getting the cgroup root at apply time.

- namespaces/exec.go
> fix typo for GetHostRootGid

- integration/exec_test.go
- mount/init.go
> integration: check a container with userns

- namespaces/nsenter/nsenter.c
- namespaces/nsenter/nsenter.go
> Changes required to keep gcc 5.0 quiet and happy.

- configs/config.go
- configs/config_test.go
- configs/mount.go
- configs/validate/config.go
- integration/template_test.go
- linux_rootfs.go
- linux_standard_init.go
- linux_userns_init.go
- nsinit/config.go
Also remove the RestrictSys bool replaced by configurable paths that the
user can specify.
> Refactor system mounts to be placed on the config

- netlink/netlink_linux.go
This should fix problem with hairpin on EL6. I have no EL6 to  try though.
/cc @phemmer
> Use netlink to set hairpin mode

- linux_console.go
- linux_userns_init.go
> Add a constant for the container console path.

- linux_container.go
- linux_init.go
- linux_network.go
- linux_rootfs.go
I don't like to do comments only PRs, but since we are trying to clean the branch might as well...
> Fixed some typos and tried to make comments read better.

- nsinit/config.go
> Add config generation for simple user namespace testing.

- cgroups/systemd/apply_systemd.go
Signed-off-by: Lei Jitang <leijitang@huawei.com>
`fs.Apply` support set `cpu.cfs_quota_us`, but `systemd.Apply` don't. This patch add systemd support   `cpu.cfs_quota_us`.
> Add systemd support cpu.cfs_quota_us and cpu.cfs_period_us

- nsinit/config.go
> Fixes bug where rootfs was empty instead of pwd when not specified.

- configs/validate/config.go
> Validation for user namespace in the config.

- NOTICE
Spotted this one when creating https://github.com/docker/docker/pull/10938
> Update copyright year in NOTICE

- capabilities_linux.go
- update-vendor.sh
- vendor/src/github.com/syndtr/gocapability/capability/capability_linux.go
- vendor/src/github.com/syndtr/gocapability/capability/enum.go
> Linux has added a new capability audit_read

- .drone.yml
- README.md
Docker-DCO-1.1-Signed-off-by: Jessie Frazelle <jess@docker.com> (github: jfrazelle)
> remove drone

- container_linux.go
- factory_linux.go
> Add init path support to allow full control of init binary

- configs/config.go
- console_linux.go
- container_linux.go
- init_linux.go
- nsinit/exec.go
- nsinit/tty.go
- process.go
- rootfs_linux.go
- standard_init_linux.go
Now you need to call Process.NewConsole to setup console for process
> Move tty configuration to Process

- Makefile
- hack/validate.sh
> Add a validate script

- README.md
> fix instructions in README

- hack/validate.sh
I'm the worst, shame, shame, shame has been brought unto my family
Docker-DCO-1.1-Signed-off-by: Jessie Frazelle <jess@docker.com> (github: jfrazelle)
> Fixes validate

- integration/execin_test.go
- process_linux.go
Before it produced panic or hanging
> Return init errors from setnsProcess

- cgroups/systemd/apply_systemd.go
It looks weird but works and not crashes application.
> Implement stats for systemd

- cgroups/cgroups.go
- cgroups/fs/apply_raw.go
- cgroups/fs/blkio.go
- cgroups/fs/blkio_test.go
- cgroups/fs/cpu.go
- cgroups/fs/cpu_test.go
- cgroups/fs/cpuacct.go
- cgroups/fs/cpuset.go
- cgroups/fs/cpuset_test.go
- cgroups/fs/devices.go
- cgroups/fs/devices_test.go
- cgroups/fs/freezer.go
- cgroups/fs/memory.go
- cgroups/fs/memory_test.go
- cgroups/fs/perf_event.go
- cgroups/fs/util_test.go
- cgroups/fs/utils.go
- cgroups/systemd/apply_nosystemd.go
- cgroups/systemd/apply_systemd.go
- container.go
- container_linux.go
- container_linux_test.go
Add a new api Set so we can change resource configs when container is running.
> add a new api Set

- integration/exec_test.go
> Adds an integration test for checking process env.

- container_linux.go
- integration/execin_test.go
- nsenter/nsexec.c
I failed to write proper test. Maybe you can help me.
> Add tty support for setnsProcess

- integration/exec_test.go
- integration/execin_test.go
- setns_init_linux.go
- standard_init_linux.go
> Pass os.Environ() as environment to process from init.

- selinux/selinux.go
Docker-DCO-1.1-Signed-off-by: Paul Morie <pmorie@gmail.com> (github: pmorie)
> Add godoc for selinux package

- cgroups/fs/memory_test.go
> add Set memoryswap test cases

- update-vendor.sh
- vendor/src/github.com/Sirupsen/logrus/.travis.yml
- vendor/src/github.com/Sirupsen/logrus/README.md
- vendor/src/github.com/Sirupsen/logrus/entry.go
- vendor/src/github.com/Sirupsen/logrus/entry_test.go
- vendor/src/github.com/Sirupsen/logrus/examples/basic/basic.go
- vendor/src/github.com/Sirupsen/logrus/exported.go
- vendor/src/github.com/Sirupsen/logrus/formatter.go
- vendor/src/github.com/Sirupsen/logrus/hooks/airbrake/airbrake.go
- vendor/src/github.com/Sirupsen/logrus/hooks/papertrail/papertrail.go
- vendor/src/github.com/Sirupsen/logrus/hooks/sentry/README.md
- vendor/src/github.com/Sirupsen/logrus/hooks/sentry/sentry.go
- vendor/src/github.com/Sirupsen/logrus/hooks/sentry/sentry_test.go
- vendor/src/github.com/Sirupsen/logrus/hooks/syslog/README.md
- vendor/src/github.com/Sirupsen/logrus/hooks/syslog/syslog.go
- vendor/src/github.com/Sirupsen/logrus/json_formatter.go
- vendor/src/github.com/Sirupsen/logrus/json_formatter_test.go
- vendor/src/github.com/Sirupsen/logrus/logger.go
- vendor/src/github.com/Sirupsen/logrus/logrus_test.go
- vendor/src/github.com/Sirupsen/logrus/terminal_notwindows.go
- vendor/src/github.com/Sirupsen/logrus/terminal_openbsd.go
- vendor/src/github.com/Sirupsen/logrus/text_formatter.go
- vendor/src/github.com/Sirupsen/logrus/text_formatter_test.go
- vendor/src/github.com/Sirupsen/logrus/writer.go
we did the same for docker/docker so now they are inline.
> Update logrus to 0.6.6

- rootfs_linux.go
> Mounting a tmpfs directory needs to inherit directory permissions from base

- nsinit/exec.go
- nsinit/main.go
- nsinit/utils.go
More people are using this to test new features and this makes it very
simple to run a container with a simple command.
`nsinit exec --tty sh`
> nsinit usability improvements

- integration/template_test.go
- nsinit/config.go
- rootfs_linux.go
> mount: Take out the base mounts and move them to the config.

- netlink/netlink_linux.go
Signed-off-by: Yuan Sun <sunyuan3@huawei.com>
> correct comment errors for netlink_linux.go

- rootfs_linux.go
> mount: Add a flag to bind devices when user namespaces are enabled.

- init_linux.go
Signed-off-by: Lei Jitang <leijitang@huawei.com>
> Fix minor typo in init_linux.go

- nsinit/README.md
Add basic build documentation for nsinit.
Fix [#467](https://github.com/docker/libcontainer/issues/467).
Ping @resouer .
> add readme for nsinit about how to build nsinit

- cgroups/systemd/apply_systemd.go
As reported in #477 the test scope may not be cleaned up between runs.
In order to fix this we must be polite and remove the scope after we
have done our test and attempt to remove an existing scope if it exists.
This way we can guarantee our test will run.
This replaces https://github.com/docker/libcontainer/pull/477
> cgroups: systemd: attempt to stop test scope, if any

- cgroups/fs/freezer.go
- cgroups/fs/freezer_test.go
> cgroups: reurn error when passing invalid argument to freezer

- cgroups/systemd/apply_systemd.go
> cgroups/systemd: Use unified subsystems

- apparmor/gen.go
> Fix: typos.

- nsinit/main.go
> Change nsinit root to /var/run/nsinit

- integration/exec_test.go
- integration/utils_test.go
> add systemd integration test

- configs/namespaces.go
- container_linux.go
- container_linux_test.go
- integration/exec_test.go
Thanks coolljit0725 for initial fix.
Closes #512
> Ensure that state always contains pathes to all namespaces

- nsinit/README.md
About how to use and explaination of available options. Fixes #468 .
Signed-off-by: Sun Jianbo <wonderflow@zju.edu.cn>
cc @resouer
Hope to be helpful.
> Add documentation for nsinit

- rootfs_linux.go
> /dev/mqueue has to be labeled correctly

- cgroups/fs/blkio.go
- cgroups/fs/blkio_test.go
- cgroups/systemd/apply_systemd.go
- configs/cgroup.go
> cgroups: add support for blkio.weight_device

- integration/execin_test.go
- nsenter/nsenter_test.go
- nsenter/nsexec.c
This fixes ExtraFiles for execin
Thanks @Mic95 for report
> Read _LIBCONTAINER_INITPIPE in nsexec.c

- integration/exec_test.go
- integration/execin_test.go
- integration/utils_test.go
- improves readability
- less typing
Signed-off-by: Jörg Thalheim <joerg@higgsboson.tk>
> integration: use test helper for error check

- factory.go
Docker-DCO-1.1-Signed-off-by: Hui Kang <hkang.sunysb@gmail.com>
> Fix a typo in factory.go

- cgroups/fs/apply_raw.go
- cgroups/fs/hugetlb.go
- cgroups/systemd/apply_systemd.go
> add cgroup subsystem hugetlb

- nsinit/exec.go
- nsinit/utils.go
> nsinit: Add a flag to enable systemd support for cgroups

- nsenter/nsexec.c
It would be easier for people to understand how nsexec really
works.
> add comments for nsexec.c

- cgroups/systemd/apply_systemd.go
> add Set support for systemd based cgroup

- nsenter/README.md
Now the README in nsenter is a little confused and hard for new commings to understand.
Signed-off-by: Sun Jianbo <wonderflow@zju.edu.cn>
> Add more explanation for nsenter

- cgroups/fs/apply_raw.go
- cgroups/systemd/apply_systemd.go
- integration/exec_test.go
Let them call the same function, and add test cases for that.
> cleanup cpushares check

- cgroups/systemd/apply_systemd.go
- configs/network.go
- console_linux.go
- container.go
- devices/devices.go
- process.go
Signed-off-by: bin liu <liubin0329@gmail.com>
> fix some typos in source code comments

- nsinit/config.go
- rootfs_linux.go
> Add cgroup mount type for mounting container local cgroups

- container_linux.go
- criu_opts.go
- nsinit/checkpoint.go
--page-server to specify the IP address of criu page server
--port to specify the port of the criu page server
Docker-DCO-1.1-Signed-off-by: Hui Kang <hkang.sunysb@gmail.com>
> Allow dumped image to be transferred to a criu page server

- cgroups/fs/blkio.go
- cgroups/fs/blkio_test.go
- cgroups/systemd/apply_systemd.go
- configs/cgroup.go
> cgroups: add support blkio.throttle.read/write_*

- cgroups/fs/apply_raw.go
- cgroups/systemd/apply_nosystemd.go
- cgroups/systemd/apply_systemd.go
> remove unused functions

- cgroups/fs/stats_util_test.go
- nsinit/oom.go
- nsinit/pause.go
> Use logrus everywhere

- cgroups/fs/stats_util_test.go
- container_linux.go
- init_linux.go
- integration/init_test.go
- nsinit/init.go
- nsinit/main.go
- nsinit/oom.go
- nsinit/pause.go
- nsinit/utils.go
Docker already did this: https://github.com/docker/docker/issues/11762
libcontainer should also do it.
> Replace aliased imports of logrus

- SPEC.md
> some fixes for SPEC

- cgroups/fs/cpu.go
- cgroups/fs/cpu_test.go
- cgroups/systemd/apply_systemd.go
- configs/cgroup.go
> croup cpu: add support for realtime throttling

- cgroups/fs/net_prio.go
- cgroups/fs/net_prio_test.go
- cgroups/systemd/apply_systemd.go
- configs/cgroup.go
- configs/interface_priority_map.go
> cgroup: add support for net_prio

- cgroups/fs/memory.go
- cgroups/fs/memory_test.go
- cgroups/systemd/apply_systemd.go
- configs/cgroup.go
> Add support for kmem limit

- cgroups/fs/apply_raw.go
- cgroups/fs/net_cls.go
- cgroups/fs/net_cls_test.go
- cgroups/systemd/apply_systemd.go
- configs/cgroup.go
> cgroups: add support for net_cls

- cgroups/systemd/apply_systemd.go
> cgroup: Add freeze Set When calls systemd to Apply

- nsinit/restore.go
Right now, you can restore any image into a container, so long as that container has been started and then checkpointed. This patch lets you restore an image into a brand new container, without first requiring you to start and checkpoint it.
> Allow restore to actually exec/create the libcontainer

- Dockerfile
- factory_linux.go
- integration/checkpoint_test.go
The test creates a "cat" process, checkpoints that process, then restores the process, making sure at each point that things are in the correct state.
> First attempt at an integration for checkpoint/restore.

- integration/exec_test.go
- integration/execin_test.go
- integration/utils_test.go
> integration: don't ignore exit codes of test processes

- cgroups/fs/memory.go
- cgroups/fs/memory_test.go
- cgroups/fs/stats_util_test.go
- cgroups/stats.go
- container_linux_test.go
> cgroup memory: Enchance stats support of memory

- nsinit/README.md
Related with #479
Signed-off-by: Sun Jianbo <wonderflow@zju.edu.cn>
> Update nsinit readme for C/R

- cgroups/fs/apply_raw.go
- cgroups/systemd/apply_systemd.go
Came across https://gist.github.com/runcom/5791bd0befbe8f0c7d3b while testing stats in Docker, hope the fix is right or fixing it Docker side is enough https://github.com/docker/docker/pull/13444
Signed-off-by: Antonio Murdaca <me@runcom.ninja>
> Fix race in stats Manager

- cgroups/fs/apply_raw.go
- cgroups/fs/hugetlb.go
- cgroups/fs/hugetlb_test.go
- cgroups/fs/stats_util_test.go
- cgroups/stats.go
- cgroups/systemd/apply_systemd.go
- cgroups/utils.go
- configs/cgroup.go
- configs/hugepage_limit.go
> hugetlb: Add support of Set and GetStats function

- hack/validate.sh
Was broken because of update in docker
ping @crosbymichael @jfrazelle
> Fix hack/validate.sh

- cgroups/utils.go
It sped up this function x10 times(because of not using Ssprintf).
It was one of two major performance drawbacks in docker, because we're parsing
this file pretty often.
> Use simpler parsing of /proc/self/mountinfo for FindCgroupMountpoint

- nsinit/README.md
Signed-off-by: Arnaud Porterie <arnaud.porterie@docker.com>
> Fix nsinit README.md config link

- cgroups/fs/memory.go
- cgroups/fs/memory_test.go
- cgroups/systemd/apply_systemd.go
- configs/cgroup.go
Signed-off-by: Raghavendra K T <raghavendra.kt@linux.vnet.ibm.com>
> Add the memory swappiness tuning support to libcontainer

- init_linux.go
> Only try to get AdditionalGroups if they are configured.

- selinux/selinux.go
Signed-off-by: Antonio Murdaca <runcom@linux.com>
> Remove unused code
